# Generated by Django 2.2.4 on 2020-07-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
