# Generated by Django 2.2.4 on 2020-07-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0003_remove_course_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of this hole (optional)')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holes', to='golfapp.Course')),
            ],
            options={
                'unique_together': {('number', 'course'), ('name', 'course')},
            },
        ),
    ]
