# Generated by Django 2.2.4 on 2020-07-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0006_auto_20200702_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('GOLD', 'Gold')], max_length=255, null=True),
        ),
    ]
