# Generated by Django 2.2.4 on 2020-07-03 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0007_tee_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='mens_par',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hole',
            name='womens_par',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_black',
            field=models.BooleanField(default=False, verbose_name='Black Tees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_blue',
            field=models.BooleanField(default=False, verbose_name='Blue Tees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_gold',
            field=models.BooleanField(default=False, verbose_name='Gold Tees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_green',
            field=models.BooleanField(default=False, verbose_name='Green Tees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_red',
            field=models.BooleanField(default=False, verbose_name='Red Tees'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tee_white',
            field=models.BooleanField(default=False, verbose_name='White Tees'),
        ),
        migrations.AlterUniqueTogether(
            name='tee',
            unique_together={('color', 'hole')},
        ),
    ]
