# Generated by Django 2.2.4 on 2020-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0009_golferuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golferuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=255),
            preserve_default=False,
        ),
    ]
