# Generated by Django 2.2.4 on 2020-07-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0010_auto_20200703_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tee',
            name='par',
        ),
    ]
