# Generated by Django 2.2.4 on 2020-07-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0011_remove_tee_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('GOLD', 'Gold')], max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tee',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tee',
            name='tee_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tees', to='golfapp.TeeSet'),
        ),
        migrations.AlterUniqueTogether(
            name='tee',
            unique_together={('number', 'tee_set')},
        ),
        migrations.RemoveField(
            model_name='tee',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='hole',
        ),
    ]
