# Generated by Django 2.2.4 on 2020-07-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0012_auto_20200703_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('GOLD', 'Gold')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tee',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tees', to='golfapp.Hole'),
        ),
        migrations.AlterUniqueTogether(
            name='tee',
            unique_together={('color', 'hole')},
        ),
        migrations.RemoveField(
            model_name='tee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='tee_set',
        ),
        migrations.DeleteModel(
            name='TeeSet',
        ),
    ]
