# Generated by Django 2.2.4 on 2020-07-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0014_teecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teecolor',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teecolors', to='golfapp.Course'),
        ),
    ]
