# Generated by Django 2.2.4 on 2020-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0015_teecolor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teecolor',
            name='course',
        ),
        migrations.AddField(
            model_name='teecolor',
            name='course',
            field=models.ManyToManyField(related_name='teecolors', to='golfapp.Course'),
        ),
    ]
