# Generated by Django 2.2.4 on 2020-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0016_auto_20200703_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teecolor',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='tee_colors',
            field=models.ManyToManyField(related_name='courses', to='golfapp.TeeColor'),
        ),
    ]
