# Generated by Django 2.2.4 on 2020-07-04 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0017_auto_20200703_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tee_black',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tee_blue',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tee_gold',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tee_green',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tee_red',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tee_white',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title this round (optional)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfapp.Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
