# Generated by Django 2.2.4 on 2020-07-04 01:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0018_auto_20200703_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='round',
            name='tee_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teecolor', to='golfapp.TeeColor'),
        ),
        migrations.AlterField(
            model_name='round',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
