# Generated by Django 2.2.4 on 2020-07-04 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0019_auto_20200703_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('hole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfapp.Hole')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfapp.Round')),
            ],
            options={
                'unique_together': {('round', 'hole')},
            },
        ),
    ]
