# Generated by Django 4.2.2 on 2023-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golfapp", "0022_coursepicture_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golferuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
