# Generated by Django 4.2.2 on 2023-06-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golfapp", "0023_alter_golferuser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hole",
            name="mens_par",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(3),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hole",
            name="womens_par",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(3),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tee",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLACK", "Black"),
                    ("BLUE", "Blue"),
                    ("GOLD", "Gold"),
                    ("GREEN", "Green"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teecolor",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLACK", "Black"),
                    ("BLUE", "Blue"),
                    ("GOLD", "Gold"),
                    ("GREEN", "Green"),
                    ("RED", "Red"),
                    ("WHITE", "White"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
